name: OpenFactions
version: 0.2.4.0
api-version: 1.7.10
main: openFactions.CustomNations
authors: [ZettaX, Inivican]
description: A backported OpenFactions for 1.7.10, aimed at delivering a better factions experience. 
commands:
   of:
      description: Main command.
      usage: /of [args]
      permission: of.main
      permission-message: You're not allowed to use this command.